namespace AssetManagement_EntityClass
{
    public class AssetManagerEntity
    {
        public string Group { get; set; }
        public string Asset_Type { get; set; }
        public string PURCHASE_UNIT { get; set; }
        public string PURCHASE_DATE_YEAR { get; set; }
        public string CPU_V { get; set; }
        public string Bill_No { get; set; }
        public string Bill_Date { get; set; }
        public string INSTALLED_UNIT { get; set; }
        public string CPU_ASSET_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT { get; set; }
        public string DEPARTMENT { get; set; }
        public string Desktop_Laptop_Server { get; set; }
        public string MachineCode { get; set; }
        public string MAKE { get; set; }
        public string Model_Number { get; set; }
        public string Machine_Sl_No { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string PROCESSOR { get; set; }
        public string Monitor { get; set; }
        public string Monitor_Asset_Code { get; set; }
        public string Monitor_Make { get; set; }
        public string Employee_Code { get; set; }
        public string Login_Id { get; set; }
        public string Ip_No { get; set; }
        public string WARRANTY_AMC { get; set; }
        public string UPTO { get; set; }
        public string MONTH { get; set; }
        public string Windows_Version1 { get; set; }
        public string Windows_Version_Installed { get; set; }
        public string Windows_Key { get; set; }
        public string Windows_COA { get; set; }
        public string Windows_License_Type_Paper_OEM { get; set; }
        public string Office { get; set; }
        public string Office_Version_Installed { get; set; }
        public string Office_Key { get; set; }
        public string Office_COA { get; set; }
        public string Office_License_Type_Paper_OEM { get; set; }
        public string USER_Mail_ID { get; set; }
        public string GIMS_ID { get; set; }
        public string VFM_ID { get; set; }
        public string PADS_ID { get; set; }
        public string Reporting_TO { get; set; }
        public string BACK_UP_USER_NAME { get; set; }
        public string Host_Name { get; set; }
        public string BATTERY_SR_NO { get; set; }
        public string ADAPTER_SR_NO { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string SERVICE_TAG { get; set; }
        public string WIFI_MACID_LAN_MACID_BLUETOOTH { get; set; }
        public string Soft { get; set; }
        public string REMARKS { get; set; }
        public string YEAR_OLD { get; set; }
        public string YEAR { get; set; }
        public string SR_NO { get; set; }
        //public string premises { get; set; }
        public string CompCode { get; set; }
        public string cartridge_No { get; set; }
        public string counter { get; set; }
        public string vendor { get; set; }
        public string Mode { get; set; }
        public string Reporting_Head { get; set; }
        public string SCCM { get; set; }
        public string Temp_Data { get; set; }
        public string Status { get; set; }
        public string Reg_Status { get; set; }
        public string SpRemark { get; set; }
        public string File1 { get; set; }
        public string spRemark_new { get; set; }
        public string Win_Flag { get; set; }
        public string Model_number_new { get; set; }
        public string ChkChecked { get; set; }
        public string U_Sr_No { get; set; }
        public string U_Remarks { get; set; }
        public string U_Sheet_No { get; set; }
        public string U_Engineer { get; set; }
        public string Billed_OS { get; set; }
        public string ActualDFlag { get; set; }
        public string Billed_Sr_no { get; set; }
        public string BILL_Vendor { get; set; }
        public string Act_Status { get; set; }
        public string Act_Date { get; set; }
        public string Actual_Damaged { get; set; }
        public string ScrapChallan { get; set; }
        public string User_type { get; set; }
        public string User_Type_Sub { get; set; }
        public string MobileNo { get; set; }
        public string Install_Date { get; set; }
        public string LoginName { get; set; }
        public string Pre_Department { get; set; }
        public string PRE_IP_NO { get; set; }
        public string PRE_user_mail_ID { get; set; }
        public string PRE_Login_ID { get; set; }
        public string PRE_INSTALLED_UNIT { get; set; }
        public string Last_login_DTTM { get; set; }
        public string Last_Enry_Count { get; set; }
        public string Last_UserName { get; set; }
        public string Last_PST_Size { get; set; }
        public string Last_PST_Checking { get; set; }
        public string Current_PST_Size { get; set; }
        public string HDD_Type { get; set; }
        public string RAM_Type { get; set; }
        public string Keyboard { get; set; }
        public string WirelessKeyboard { get; set; }
        public string Mouse { get; set; }
        public string Screen_Size { get; set; }
        public string RemoteAllowed { get; set; }
        public string Switch_Lic_Bill_No { get; set; }
        public string Invoice_Ta { get; set; }
        public string VehicleType { get; set; }
        public string Price { get; set; }
        public string UsedBy { get; set; }
        public string Asset_Name { get; set; }
        public string Resolution { get; set; }
        public string Panel_Type { get; set; }
        public string Generation { get; set; }
        public string Printer_Type { get; set; }
        public string Rental_Company { get; set; }
        public string RentStartDate { get; set; }
        public string RentEndDate { get; set; }
        public string PrintSpeed { get; set; }
        public string PaperCapacity { get; set; }
        public string Firewall_Type { get; set; }
        public string Port_Count { get; set; }
        public string Throughput { get; set; }
        public string RecognitionType { get; set; }
        public string UserCapacity { get; set; }
        public string Connectivity { get; set; }
        public string ChairType { get; set; }
        public string Material { get; set; }
        public string Color { get; set; }
        public string CoolingCapacityTon { get; set; }
        public string EnergyRating { get; set; }
        public string InstallationLocation { get; set; }
        public string NoiseLevels { get; set; }
        public string RegistrationNo { get; set; }
        public string EngineNo { get; set; }
        public string FuelType { get; set; }
        public string WarrantyValidity { get; set; }
        public string PrinterPaper_Capacity { get; set; }
        public string NoiseLevel { get; set; }
        public System.Boolean Active { get; set; }
        public string AssetCode { get; set; }
        public string MType { get; set; }
        public string ActionType { get; set; }
        public string Remark { get; set; }
        public string HddRamType { get; set; }
        public string Capacity { get; set; }
        public string ChangeDate { get; set; }
        public string HddUsage { get; set; }
        public string FromUser { get; set; }
        public string TargetUser { get; set; }
        public string Premises { get; set; }
        public string Email_ID { get; set; }
        public string Designation { get; set; }
        public string EngineerName { get; set; }
        public string ToUserName { get; set; }
        public string ScrapTransfer { get; set; }
        public string ScrapRemark { get; set; }
        public string ContactExtNo { get; set; }
        public string MonitorSrNo { get; set; }
        public Boolean With_Monitor { get; set; }
        public string Software { get; set; }
        public string SoftwareVersion { get; set; }
        public string SoftwareKey { get; set; }
        public string SoftwareLicence { get; set; }

    }
}
